services:
  hamlib-server:
    container_name: hamlib-server
    image: hammusings/hamlib-server:4.6.5
    ports:
      - 45320:4532
    environment:
      - MODEL=1
      - BAUD=38400
      - AUTO_POWER_ON=0
      - AUTO_POWER_OFF=0
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB0
    restart: unless-stopped
networks: {}